#!/usr/bin/env python3
"""
scripts/sync-models.py — Propagate agents/models.yml to every place model names live.

Single source of truth: agents/models.yml. This script rewrites:

  1. agents/swarm-*.md frontmatter  (model: / fallback_models: lines only)
  2. ~/.qoder/agents/swarm-*.md     (installed copies)
  3. README.md                      (table between MODEL-BINDINGS markers)
  4. skills/swarm/references/_shared.md  (model cells in the routing table)

Usage:
  python3 scripts/sync-models.py            validate + apply
  python3 scripts/sync-models.py --check    dry-run; exit 1 on drift/invalid (CI)
  python3 scripts/sync-models.py --auto-fix remap vanished catalog models, then apply

Auto-fix rules (in order):
  a) vanished `*-DogFooding` model + exactly one `*DogFooding*` in catalog → remap
  b) first fallback_models entry still valid → promote to primary
  c) otherwise → error, nothing written

Catalog validation needs `qodercli --list-models`. Without qodercli (e.g. AoneCI
runner) the script degrades to drift-only mode and warns.
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
MODELS_YML = REPO_ROOT / "agents" / "models.yml"
AGENTS_DIR = REPO_ROOT / "agents"
INSTALLED_DIR = Path.home() / ".qoder" / "agents"
README = REPO_ROOT / "README.md"
SHARED = REPO_ROOT / "skills" / "swarm" / "references" / "_shared.md"

BEGIN = "<!-- MODEL-BINDINGS:BEGIN — auto-generated by scripts/sync-models.py; edit agents/models.yml instead -->"
END = "<!-- MODEL-BINDINGS:END -->"


def load_roles() -> dict:
    data = yaml.safe_load(MODELS_YML.read_text())
    if not isinstance(data, dict) or not data:
        sys.exit(f"error: {MODELS_YML} is empty or not a mapping")
    return data


def catalog() -> list[str] | None:
    cli = shutil.which("qodercli")
    if not cli:
        return None
    out = subprocess.run([cli, "--list-models"], capture_output=True, text=True).stdout
    names = []
    for line in out.splitlines():
        line = re.sub(r"\s+\(.*\)$", "", line).strip()
        if line and line != "MODEL":
            names.append(line)
    return names


def auto_fix(roles: dict, cat: list[str], yml_text: str) -> tuple[dict, str, list[str]]:
    notes = []
    dogfooding = [m for m in cat if "DogFooding" in m]
    for role, cfg in roles.items():
        model = cfg["model"]
        if model in cat:
            continue
        if "DogFooding" in model and len(dogfooding) == 1:
            new = dogfooding[0]
            notes.append(f"{role}: {model} → {new} (dogfooding rename)")
        else:
            valid_fb = [fb for fb in cfg.get("fallback_models", []) if fb in cat]
            if not valid_fb:
                sys.exit(f"error: {role}.model '{model}' not in catalog and no valid fallback")
            new = valid_fb[0]
            cfg["fallback_models"] = [fb for fb in cfg["fallback_models"] if fb != new]
            notes.append(f"{role}: {model} → {new} (promoted fallback)")
        cfg["model"] = new
        # line-level write-back so yml comments survive
        block = re.search(rf"(^{re.escape(role)}:\n(?:  .*\n)+)", yml_text, re.M)
        if not block:
            sys.exit(f"error: cannot locate block for {role} in {MODELS_YML}")
        new_block = re.sub(r"^  model: .*$", f"  model: {new}", block.group(1), count=1, flags=re.M)
        fb = cfg["fallback_models"]
        new_block = re.sub(
            r"^  fallback_models: .*$",
            f"  fallback_models: [{', '.join(fb)}]" if fb else "  fallback_models: []",
            new_block, count=1, flags=re.M,
        )
        yml_text = yml_text.replace(block.group(1), new_block)
    return roles, yml_text, notes


def frontmatter_update(path: Path, model: str, fallbacks: list[str]) -> bool:
    text = path.read_text()
    m = re.match(r"(?s)(---\n)(.*?)(\n---\n)(.*)", text)
    if not m:
        sys.exit(f"error: {path} has no frontmatter block")
    head, fm, tail = m.group(1), m.group(2), m.group(4)
    fb_line = f"fallback_models: [{', '.join(fallbacks)}]" if fallbacks else "fallback_models: []"
    fm_new = re.sub(r"^model: .*$", f"model: {model}", fm, count=1, flags=re.M)
    if re.search(r"^fallback_models: ", fm_new, re.M):
        fm_new = re.sub(r"^fallback_models: .*$", fb_line, fm_new, count=1, flags=re.M)
    else:
        fm_new = re.sub(r"^(model: .*)$", rf"\1\n{fb_line}", fm_new, count=1, flags=re.M)
    new_text = head + fm_new + m.group(3) + tail
    if new_text != text:
        path.write_text(new_text)
        return True
    return False


def readme_table(roles: dict) -> str:
    rows = ["| Agent | Default model | Cost tier |", "|-------|--------------|-----------|"]
    for role, cfg in roles.items():
        cost = cfg["cost"]
        label = f"{cost:.2f}x (free)" if cost == 0 else f"{cost:.2f}x"
        rows.append(f"| {role} | {cfg['model']} | {label} |")
    return "\n".join(rows)


def readme_update(roles: dict) -> bool:
    text = README.read_text()
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(text):
        sys.exit("error: MODEL-BINDINGS markers not found in README.md")
    new = pat.sub(f"{BEGIN}\n{readme_table(roles)}\n{END}", text)
    if new != text:
        README.write_text(new)
        return True
    return False


def shared_update(roles: dict) -> bool:
    lines = SHARED.read_text().splitlines(keepends=True)
    changed = False
    for i, line in enumerate(lines):
        if not line.startswith("|"):
            continue
        cells = line.split("|")
        # cells: ['', ' Role ', ' `swarm-x` ', ' `Model` ', ' `Effort` ', ...]
        if len(cells) < 5:
            continue
        for role, cfg in roles.items():
            if cells[2].strip() == f"`{role}`":
                new_cell = f" `{cfg['model']}` "
                if cells[3] != new_cell:
                    cells[3] = new_cell
                    lines[i] = "|".join(cells)
                    changed = True
    if changed:
        SHARED.write_text("".join(lines))
    return changed


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="dry-run; exit 1 on drift/invalid")
    ap.add_argument("--auto-fix", action="store_true", help="remap vanished catalog models")
    args = ap.parse_args()

    roles = load_roles()
    cat = catalog()
    if cat is None:
        print("warn: qodercli not found — drift-only mode (no catalog validation)")
    else:
        missing = [(r, c["model"]) for r, c in roles.items() if c["model"] not in cat]
        missing += [(r, fb) for r, c in roles.items() for fb in c.get("fallback_models", []) if fb not in cat]
        if missing and not args.auto_fix:
            for role, m in missing:
                print(f"✗ {role}: '{m}' not in catalog")
            print("\nrun with --auto-fix to remap, or edit agents/models.yml")
            return 1
        if missing and args.auto_fix and not args.check:
            roles, yml_text, notes = auto_fix(roles, cat, MODELS_YML.read_text())
            MODELS_YML.write_text(yml_text)
            for n in notes:
                print(f"auto-fix: {n}")

    changed = []
    for role, cfg in roles.items():
        f = AGENTS_DIR / f"{role}.md"
        if not f.exists():
            sys.exit(f"error: {f} missing (role in models.yml has no agent file)")
        if frontmatter_update(f, cfg["model"], cfg.get("fallback_models", [])):
            changed.append(str(f.relative_to(REPO_ROOT)))
    if readme_update(roles):
        changed.append("README.md")
    if shared_update(roles):
        changed.append("skills/swarm/references/_shared.md")

    if args.check:
        if changed:
            print("drift detected (run sync-models.py to apply):")
            for c in changed:
                print(f"  ✗ {c}")
            return 1
        print("OK: models.yml, frontmatter, and docs are in sync"
              + ("; catalog valid" if cat else "; catalog NOT validated"))
        return 0

    for f in AGENTS_DIR.glob("swarm-*.md"):
        if INSTALLED_DIR.is_dir():
            shutil.copy2(f, INSTALLED_DIR / f.name)
    if INSTALLED_DIR.is_dir():
        changed.append("~/.qoder/agents/ (synced)")

    print("synced:" if changed else "already in sync — nothing to do")
    for c in changed:
        print(f"  ✓ {c}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
